services:
  - type: web
    name: crypto-broker-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run broker_info.py --server.port 10000 --server.address 0.0.0.0
    plan: free
